<a href="https://colab.research.google.com/github/ruhulamin005/Data-science-hacks/blob/main/arff_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# *Load .arff dataset in colab*

In [ ]:
#ARFF = Attribute-Relation File Format

In [ ]:
import pandas as pd
from scipy.io import arff

In [ ]:
maldata = arff.loadarff('/content/drive/MyDrive/Colab Notebooks/bone-marrow.arff')

In [ ]:
df = pd.DataFrame(maldata[0])

In [ ]:
df.head()

   donor_age donor_age_below_35  ... survival_time survival_status
0  22.830137             b'yes'  ...         999.0            b'0'
1  23.342466             b'yes'  ...         163.0            b'1'
2  26.394521             b'yes'  ...         435.0            b'1'
3  39.684932              b'no'  ...          53.0            b'1'
4  33.358904             b'yes'  ...        2043.0            b'0'

[5 rows x 37 columns]